name: Does Project Compile

on: push
  
jobs:
    build:
      runs-on: ubuntu-latest
        
      steps:
        - uses: actions/checkout@v2.5.0
          with:
        
        - uses: actions/cache@v3
          with:
            path: ~/.nuget/packages
            key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
            restore-keys: |
              ${{ runner.os }}-nuget-
        
        - uses: game-ci/unity-builder@v2.1.2

